---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k3d-mycluster-system
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./.weave-gitops/clusters/k3d-mycluster/system
  prune: true
  sourceRef:
    kind: GitRepository
    name: wego-auto-github-weave-test

