apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: k3d-mycluster
  namespace: wego-system
resources:
- gitops-runtime.yaml
- flux-source-resource.yaml
- flux-system-kustomization-resource.yaml
- flux-user-kustomization-resource.yaml
- wego-app.yaml
