apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: weave_test
  namespace: wego-system
resources:
- app.yaml
- weave_test-gitops-deploy.yaml
- weave_test-gitops-source.yaml
